foreground   #ced3d8
background   #050B11
cursor       #ced3d8

color0       #050B11
color8       #909397
color1       #779098
color9       #779098
color2       #7999A6
color10      #7999A6
color3       #8CA8B4
color11      #8CA8B4
color4       #A1A1A3
color12      #A1A1A3
color5       #CCB2A0
color13      #CCB2A0
color6       #D7CCB7
color14      #D7CCB7
color7       #ced3d8
color15      #ced3d8
